FROM jboss/keycloak-mysql:latest

ADD CAMPAIGN_REALM-realm.json /opt/jboss/keycloak/

ENTRYPOINT [ "/opt/jboss/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0", "-Dkeycloak.import=/opt/jboss/keycloak/CAMPAIGN_REALM-realm.json"]